export const ActionTypes = {
  INCREMENT_COUNTER: "INCREMENT_COUNTER",
  DECREMENT_COUNTER: "DECREMENT_COUNTER",
  ADD_BY_NUMBER: "ADD_BY_NUMBER",
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
};
